project: "DETR_SWEEP_v2"
entity: "Team5-C5"
program: main_sweep.py
method: grid
metric:
  name: val/mAP_0.50_0.95_all
  goal: maximize

parameters:
  lora_combo:
    values:
      # - name: "1_Academic_Baseline"
      #   lora_r: 8
      #   lora_alpha: 32
      #   learning_rate: 0.0001
      
      # - name: "2_High_Capacity"
      #   lora_r: 16
      #   lora_alpha: 32
      #   learning_rate: 0.0001
        
      # - name: "3_Heavy_Injection"
      #   lora_r: 8
      #   lora_alpha: 64
      #   learning_rate: 0.0001
        
      # - name: "4_Aggressive_LR"
      #   lora_r: 8
      #   lora_alpha: 32
      #   learning_rate: 0.0005
        
      # - name: "5_Extreme_Efficiency"
      #   lora_r: 4
      #   lora_alpha: 16
      #   learning_rate: 0.0005
      - name: "1_Academic_Baseline"
        lora_r: 8
        lora_alpha: 32
        learning_rate: 0.00001  # Tu base de 1e-5

      - name: "2_High_Capacity"
        lora_r: 16
        lora_alpha: 32
        learning_rate: 0.00001  # Más capacidad (r=16), pero aprendiendo lento
        
      - name: "3_Heavy_Injection"
        lora_r: 8
        lora_alpha: 64          # Mucho peso a los nuevos features (alpha=64)
        learning_rate: 0.00001
        
      - name: "4_Aggressive_LR"
        lora_r: 8
        lora_alpha: 32
        learning_rate: 0.00005  # 5e-5: Un punto intermedio para ver si acelera la curva
        
      - name: "5_Extreme_Efficiency"
        lora_r: 8
        lora_alpha: 32
        learning_rate: 0.0001   # 1e-4: El estándar de LoRA, para comparar directamente con el exp 1

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config"
  - "configs/sweeps/lora_baseline.json"