#!/bin/bash 
#SBATCH -n 4                    # Number of cores
#SBATCH --mem 20000             # 16GB asked
#SBATCH -p mlow                # Choose mlow to submit to master low prioriy queue
#SBATCH --gres gpu:1            # To ask Pascales MAX 8
#SBATCH -o logs/out_%u_%j.log   # File to which STDOUT will be written
#SBATCH -e logs/err_%u_%j.log   # File to which STDERR will be written

python train.py --config configs/resnet50_gru_gerard_test2.json
python train.py --config configs/resnet50_gru_gerard_test3.json