#!/bin/bash 
#SBATCH -n 8                  # Number of cores
#SBATCH --mem 20000             # 16GB asked
#SBATCH -p mhigh                # Choose mlow to submit to master low prioriy queue
#SBATCH --gres gpu:1            # To ask Pascales MAX 8
#SBATCH -o logs/%u_%j_out.log   # File to which STDOUT will be written
#SBATCH -e logs/%u_%j_err.log   # File to which STDERR will be written

python train.py --config configs/vit_frozen_gpt2_train.json

