#!/bin/bash 
#SBATCH -n 4                    # Number of cores
#SBATCH --mem 20000             # 16GB asked
#SBATCH -p mhigh                # Choose mlow to submit to master low prioriy queue
#SBATCH -q masterhigh           # Requeue other users mlow jobs
#SBATCH --gres gpu:1            # To ask Pascales MAX 8
#SBATCH -o logs/out_%u_%j.log   # File to which STDOUT will be written
#SBATCH -e logs/err_%u_%j.log   # File to which STDERR will be written

# source activate c5_env


# python main.py --config configs/DETR/step0_detr_inference.json

# python main.py --config configs/DETR/step1_detr_head_baseline.json

# python main.py --config configs/DETR/step2_detr_augs_basic.json

# python main.py --config configs/DETR/step2_detr_augs_weather.json

# python main.py --config configs/DETR/step3_detr_full_finetune.json

# python main.py --config configs/DETR/step3_detr_full_finetune_lora.json

# python main.py --config configs/FRNN/step1_frnn_head_baseline.json

# python main.py --config configs/FRNN/step2_frnn_augs_basic.json

# python main.py --config configs/FRNN/step2_frnn_augs_weather.json

# python main.py --config configs/RT_DETR/rt_detr.json

# python main.py --config configs/FRNN/step3_frnn_full_finetune_partial.json

# python main.py --config configs/DETR/detr_DeART_inference.json

# python main.py --config configs/FRNN/frnn_DeART_inference.json

# python main.py --config configs/DETR/detr_DeART_head_noaug.json

# python main.py --config configs/DETR/detr_DeART_head_augbasic.json

python main.py --config configs/RT_DETR/rt_detr_inference.json