#!/bin/bash
#SBATCH -n 4
#SBATCH --mem 24G
#SBATCH -p mlow
#SBATCH --gres gpu:1
#SBATCH -o logs/sweeps/sweep_%u_%j.out
#SBATCH -e logs/sweeps/sweep_%u_%j.err

SWEEP_ID=$1
PROJECT=$2
COUNT=$3

if [ -z "$SWEEP_ID" ] || [ -z "$PROJECT" ]; then
  echo "Usage: sbatch job_hyp.sh <SWEEP_ID> <PROJECT_NAME> [COUNT]"
  exit 1
fi

source /ghome/group04/miniconda3/etc/profile.d/conda.sh
conda activate c5

if [ -z "$COUNT" ]; then
    echo "Starting WandB agent for sweep: $SWEEP_ID in project $PROJECT (Unlimited)"
    wandb agent Team5-C5/$PROJECT/$SWEEP_ID
else
    echo "Starting WandB agent for sweep: $SWEEP_ID in project $PROJECT (Limit: $COUNT runs)"
    wandb agent --count $COUNT Team5-C5/$PROJECT/$SWEEP_ID
fi