#!/bin/bash
#SBATCH -n 8
#SBATCH --mem 20000
#SBATCH -p mhigh
#SBATCH -q masterhigh
#SBATCH --gres gpu:1
#SBATCH -o logs/yolo_smoke_%u_%j.out
#SBATCH -e logs/yolo_smoke_%u_%j.err


DATA=~/KITTI-MOTS_YOLO/data.yaml
MODEL=yolo26x.pt

yolo detect train \
  model=$MODEL \
  data=$DATA \
  imgsz=640 epochs=3 batch=16 device=0 \
  workers=8